### ISSUE TITLE
Page cuts off on phone picture

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/awallet-landing-page#15]
<img width="1216" alt="Screen Shot 2019-09-09 at 12 53 53 pm" src="https://user-images.githubusercontent.com/16630514/64500545-fa0b0e00-d300-11e9-959a-95ffb9dd64a1.png">

**Comment by developerpeachy** [comment]
this should be fixed now, can you test this on your screen please? https://5d887dc6334fe20008fd446e--alphawallet.netlify.com
