### ISSUE TITLE
Big vertical gap at the top on mobile for pages other than /

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/awallet-landing-page#21]
The spacing looks similar on the desktop, but on mobile:

/|Others like /about, /tech
-|-
<img src="https://user-images.githubusercontent.com/56189/65309272-5520e880-dbbe-11e9-92a5-63883ed73a34.PNG" width=200>|<img src="https://user-images.githubusercontent.com/56189/65309273-55b97f00-dbbe-11e9-8475-fbe5ee09be4f.PNG" width=200>

**Comment by developerpeachy** [comment]
This should be fixed now: https://5d887dc6334fe20008fd446e--alphawallet.netlify.com/ 
<img width="303" alt="Screen Shot 2019-09-24 at 9 15 36 am" src="https://user-images.githubusercontent.com/13824586/65469760-e8526a80-deab-11e9-8028-c532b7b0ec57.png">
