### ISSUE TITLE
Fill content of devcon pages 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/awallet-landing-page#30]
Can email them to me or Rosie and fill them out on the website

**Comment by developerpeachy** [comment]
https://5d92daf2bf42bc00079c9df8--alphawallet.netlify.com/defiwtf
https://5d92daf2bf42bc00079c9df8--alphawallet.netlify.com/cryptophia 
https://5d92daf2bf42bc00079c9df8--alphawallet.netlify.com/devcon5

**Comment by zhangzhongnan928** [comment]
For DeFi,

DeFI.WTF LIVE AT DEVCON5 | OSAKA, JAPAN.

Discover DeFi with DeFi.WTF

As a celebration of DeFi.WTF at Devcon 5 this year, we are giving away some DeFi SmartTokens 

Dai, xDai, cDAI, iDAI, pDai, 
cZRX, cREP, cBAT, cUSDC,cWBTC
ETH, wETH, pETH,cETH
pUSDT, USDx, DeFi.WTF and more.

Download AlphaWallet

How to claim your SmartToken.

After installing AlphaWallet
1. Open the AlphaWallet and click the Discovery Token.
2. Tap on 'Discover' button at the bottom.
3. Tap 'Confirm' and “OK” to get your SmartTokens.

How to use your SmartToken.
Tap on your StmatTokens as you are using any app.

If you still can’t figure out how to do it, speak to the guys with AlphaWallet T-shirt or find us here.
t.me/AlphaWalletGroup

**Comment by zhangzhongnan928** [comment]
For Gift 

Ethereum lightning talks by ETHPLANET

Experience DeFi with ETHPLANET

As a celebration of Ethereum lightning talks at Devcon 5 this year, we are giving away some DeFi SmartTokens

Dai, xDai, cDAI, iDAI, pDai,
cZRX, cREP, cBAT, cUSDC,cWBTC
ETH, wETH, pETH,cETH
pUSDT, USDx and more.

Download AlphaWallet

How to claim your SmartToken.

After installing AlphaWallet

Open the AlphaWallet and click the Discovery Token.
Tap on 'Discover' button at the bottom.
Tap 'Confirm' and “OK” to get your SmartTokens.
How to use your SmartToken.
Tap on your StmatTokens as you are using any app.

If you still can’t figure out how to do it, speak to the guys with AlphaWallet T-shirt or find us here.
t.me/AlphaWalletGroup

**Comment by developerpeachy** [comment]
New content updated: 
https://5d92f6f3827ec70008d18a3f--alphawallet.netlify.com/devcon5 
https://5d92f6f3827ec70008d18a3f--alphawallet.netlify.com/defi
https://5d92f6f3827ec70008d18a3f--alphawallet.netlify.com/gift

Note that you should test this on mobile.

**Comment by developerpeachy** [comment]
This should be done on #29

**Comment by zhangzhongnan928** [comment]
https://5d92f6f3827ec70008d18a3f--alphawallet.netlify.com/devcon5
use "My keys are guarded by [Secure Enclave](https://medium.com/alphawallet/alphawallet-2-10-your-keys-in-good-hands-3567d7537cfa), how is yours?" 
to replace 
"ALPHAWALLET LIVE AT DEVCON5 | OSAKA, JAPAN."

**Comment by zhangzhongnan928** [comment]
Gift page on and after 8th Oct
Use
"A special gift from AlphaWallet, MakerDAO, DDEX, dForce, bZx and Compound 
Experience DeFi with AlphaWallet and TokenScript
As a celebration of Devcon 5 this year, we are giving away some DeFi SmartTokens"
to replace
"ETHEREUM LIGHTNING TALKS BY ETHPLANET
Experience DeFi with ETHPLANET
As a celebration of Ethereum lightning talks at Devcon 5 this year, we are giving away some DeFi SmartTokens"

**Comment by developerpeachy** [comment]
Test: https://5d955a44c071730008a67109--alphawallet.netlify.com/gift 
https://5d955a44c071730008a67109--alphawallet.netlify.com/devcon5
https://5d955a44c071730008a67109--alphawallet.netlify.com/defi

note that the content will change automatically after the 8/10/2019

**Comment by zhangzhongnan928** [comment]
![0A94E979-5275-4AD6-A821-52FCCCEBCC62](https://user-images.githubusercontent.com/33795543/66095425-cdce6e80-e5da-11e9-8569-81f40d2209be.jpeg)

These words are a bit hard to read.

**Comment by developerpeachy** [comment]
This better?

![Screen Shot 2019-10-03 at 2 08 31 pm](https://user-images.githubusercontent.com/13824586/66098779-53581b80-e5e7-11e9-9847-3ff173527caf.png)

**Comment by zhangzhongnan928** [comment]
Add 👇 at the end of each page
How to use your SmartToken.
Tap on your StmatTokens as you are using any app.

**Comment by zhangzhongnan928** [comment]
Please remove xDai, wETH and DeFi.WTF from all the landing pages

![D3ECB927-9963-4046-9256-56F2330466B2](https://user-images.githubusercontent.com/33795543/66255614-092e9000-e7c9-11e9-897b-3e039fa53981.jpeg)

**Comment by developerpeachy** [comment]
Fixed: #33
