### ISSUE TITLE
Illustration not rendering

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/awallet-landing-page#7]
I should've tested this before approving the PR, but basically the image doesn't render anymore but used to.

<img width="466" alt="Screen Shot 2019-09-03 at 11 27 32 am" src="https://user-images.githubusercontent.com/16630514/64137900-ffb6ae80-ce3d-11e9-85a0-41874b8ee90b.png">

**Comment by developerpeachy** [comment]
This is working now. Please clear your browser and try again

![Screen Shot 2019-09-03 at 4 19 47 pm](https://user-images.githubusercontent.com/13824586/64153022-3a860a00-ce71-11e9-867e-5d717b5140a0.png)

**Comment by James-Sangalli** [comment]
Refreshed
