### ISSUE TITLE
Some links in footer are broken when cmd+click / open in tabs

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/awallet-landing-page#8]
eg. The link https://alphawallet.com/tech in both header and footer is broken.

But Telegram in the footer works.

**Comment by developerpeachy** [comment]
- Social links work OK 
- Am working on routing in between pages, from different tabs.

**Comment by hboon** [comment]
Those pages with issues look like they are created dynamically in JavaScript so the URLs don’t map to actually content.

**Comment by developerpeachy** [comment]
I hope this PR will fix those links. 

The blogPosts will not work with this fix, as they are dynamically typed but will investigate this 

https://github.com/AlphaWallet/awallet-landing-page/pull/11/commits

**Comment by hboon** [comment]
Totally irrelevant to this issue or PR:

1. It's slightly better to refer to the issue in the PR rather than the other way round. You can let GitHub close the issue automatically with keywords: https://help.github.com/en/articles/closing-issues-using-keywords
2. You can use something like #11 instead of the full URL if it's the same repo.

**Comment by hboon** [comment]
@developerpeachy when you work on this, can you start with fixing https://alphawallet.com/privacy-policy/? It's a URL submitted to Apple and we are currently being reviewed. So just to be safe.

**Comment by developerpeachy** [comment]
This should be fixed now: https://5d887dc6334fe20008fd446e--alphawallet.netlify.com/
