### ISSUE TITLE
Update the partner section

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/awallet-landing-page#9]
<img width="1031" alt="Screen Shot 2019-09-04 at 8 46 14 am" src="https://user-images.githubusercontent.com/33795543/64214077-61d0eb80-cef2-11e9-8667-88c3f8f580e8.png">

Plus the link for each partner

**Comment by developerpeachy** [comment]
I have modified the staging website but it is not yet pushed to staging, if you can review this and let me know if it's okay 

![Screen Shot 2019-09-23 at 9 57 04 am](https://user-images.githubusercontent.com/13824586/65396866-4e78b800-ddee-11e9-8cf0-0b44d0923219.png)

**Comment by zhangzhongnan928** [comment]
Ok

> I have modified the staging website but it is not yet pushed to staging, if you can review this and let me know if it's okay
> 
> ![Screen Shot 2019-09-23 at 9 57 04 am](https://user-images.githubusercontent.com/13824586/65396866-4e78b800-ddee-11e9-8cf0-0b44d0923219.png)

Ok
